export enum TaskStatus {
    PENDING = 'PENDING',
    UPCOMING = 'UPCOMING',
    IN_PROGRESS = 'IN_PROGRESS',
    COMPLETED = 'COMPLETED',
    DELAYED = 'DELAYED',
    REQUEST_FOR_CLOSURE = 'REQUEST_FOR_CLOSURE',
    REQUEST_FOR_EXTENSION = 'REQUEST_FOR_EXTENSION',
    CLOSED = 'CLOSED'
}


